### ISSUE TITLE
CI checks for changelog entries

### ISSUE THREAD

**Issue by guseggert** [ipdxco/changelog-driven-release#5]
It would be awesome if we could have CI checks so that each commit either needs to add a changelog entry, or explicitly opt-out of it (e.g. with "nochangelog" in commit message). This would ensure that each commit gets a changelog entry so that there's not a scramble at release time from folks forgetting to add changelog entries.

**Comment by galargh** [comment]
This is out of scope for this project. We're going to work on custom solution for boxo/kubo separately.
